name: GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-to-ghcr:
    name: Build and push image for commit
    runs-on: ubuntu-latest
    if: github.repository == 'WordPress/openverse-frontend'

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get raw tags
        id: raw-tags
        run: |
          echo '::set-output name=push_tag::${{ github.event_name == 'push' && 'type=raw,value=main' || '' }}'
          pr_tag='pr-${{ github.event_name == 'pull_request' && github.event.pull_request.number || '' }}'
          echo "::set-output name=pr_tag::type=raw,value=$pr_tag"

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/wordpress/openverse-frontend
          tags: |
            type=sha
            type=ref,event=tag
            ${{ steps.raw-tags.outputs.push_tag }}
            ${{ steps.raw-tags.outputs.pr_tag }}

      - uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

      - name: Docker instructions
        if: github.event_name == 'pull_request'
        run: |
          echo "\
          # Container image run instructions

          If you have a local container runtime like Docker you can run this branch's code using the image and tag below:

          ```
          ghcr.io/wordpress/openverse-frontend:pr-${{ github.event.pull_request.number }}
          ```

          For example, with Docker you should run:

          ```
          docker run -it -p 127.0.0.1:8443:8443/tcp ghcr.io/wordpress/openverse-frontend:pr-${{ github.event.pull_request.number }}
          ```
          " >> $GITHUB_STEP_SUMMARY
